export { default as Home } from "./Home";
export { default as Admin } from "./Admin";
export { default as BookList } from "./BookList";
export { default as Error404 } from './Error404'
export { default as Auth } from './Auth'
export { default as UserHistory } from './UserHistory'
export { default as searchPage } from './searchPage'
export { default as BookDetail } from './BookDetail'
export { default as MyBooksPage } from './MyBooksPage'
